name = "teachsg"
compatibility_date = "2024-09-28"
pages_build_output_dir = "public"

# KV namespace for response caching
[[kv_namespaces]]
binding = "RESPONSE_CACHE"
id = "dcf77d2e6513414a9aedcc5a28d549a8"

# Workers AI binding
[ai]
binding = "AI"

[env.production]
compatibility_date = "2024-09-28"

[[env.production.kv_namespaces]]
binding = "RESPONSE_CACHE"
id = "dcf77d2e6513414a9aedcc5a28d549a8"

[env.production.ai]
binding = "AI"

[[env.production.vars]]
ANTHROPIC_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

[env.preview]
compatibility_date = "2024-09-28"

[[env.preview.vars]]
ANTHROPIC_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""