name = "teach-sg"
compatibility_date = "2024-09-28"
pages_build_output_dir = "public"

[env.production]
compatibility_date = "2024-09-28"

[[env.production.vars]]
ANTHROPIC_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

[env.preview]
compatibility_date = "2024-09-28"

[[env.preview.vars]]
ANTHROPIC_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""